### ISSUE TITLE
Fix issue with `tfn.mplstyle` not being included in package

### ISSUE THREAD

**Issue by wsp-mbuckley** [Transport-for-the-North/caf.viz#3]
The `tfn.mplstyle` file isn't being included in the caf.viz package, when installed using pip. The package setup files need updating to make sure it's included.

**Comment by MattBuckley-TfN** [comment]
> Fixed in #5

This hasn't been fixed yet

**Comment by MattBuckley-TfN** [comment]
Add the file path to pyproject.toml 

https://github.com/Transport-for-the-North/caf.viz/blob/bacef6bd21be06467246f147b952ec6bc4936bc1/pyproject.toml#L53
